web:
  service:
    api:
      type: LoadBalancer
concourse:
  worker:
    baggageclaim:
      driver: detect
  web:
    auth:
      mainTeam:
        localUser: admin
    bindPort: 80
    tls:
      enabled: true
      bindPort: 443
    kubernetes:
      teams:
      - main
      - test
    prometheus:
      enabled: true
