---
resource_types:
- name: terraform
  type: registry-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
- name: helm-chart
  type: registry-image
  source:
    repository: jghiloni/helm-chart-resource
    tag: v0.1.1

resources:
- name: concourse-helm-repo
  type: git
  icon: github
  source:
    uri: git@github.com:EngineerBetter/concourse-helm.git
    private_key: ((github_private_key))

- name: concourse-helm-chart
  type: helm-chart
  icon: ship-wheel
  source:
    repository_url: https://concourse-charts.storage.googleapis.com
    chart: concourse

- name: helm-image
  type: registry-image
  icon: docker
  source:
    repository: alpine/k8s
    tag: 1.17.5

- name: pcf-ops
  type: registry-image
  icon: docker
  source:
    repository: engineerbetter/pcf-ops

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: concourse-helm-repo
    trigger: true
  - set_pipeline: ((env))-helm
    file: concourse-helm-repo/ci/pipeline.yml
    vars:
      env: ((env))

- name: deploy-concourse
  serial: true
  plan:
  - in_parallel:
    - get: concourse-helm-repo
      trigger: true
      passed:
      - set-pipeline
    - get: concourse-helm-chart
      trigger: true
      params:
        skip_download: true
    - get: helm-image
  - task: helm-upgrade
    image: helm-image
    file: concourse-helm-repo/ci/tasks/helm-upgrade/task.yml
    params:
      ADMIN_PASSWORD: ((admin_password))
      ENV: ((env))
      GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((gcp_service_account_json))
      KUBECONFIG_CONTENTS: ((kubeconfig))
      LB_IP: ((lb_ip))
      WEB_DOMAIN: ((web_domain))
      WEB_TLS_CERT: ((web_tls.certificate))
      WEB_TLS_KEY: ((web_tls.private_key))
      WORKER_KEY: ((worker_key.private_key))
      WORKER_KEY_PUB: ((worker_key.public_key))

- name: test-concourse
  serial: true
  plan:
  - in_parallel:
    - get: concourse-helm-repo
      trigger: true
      passed:
      - deploy-concourse
    - get: concourse-helm-chart
      trigger: true
      params:
        skip_download: true
    - get: pcf-ops
  - task: run-test
    image: pcf-ops
    file: concourse-helm-repo/ci/tasks/test/task.yml
    params:
      ADMIN_PASSWORD: ((admin_password))
      GOOGLE_APPLICATION_CREDENTIALS_CONTENTS: ((gcp_service_account_json))
      KUBECONFIG_CONTENTS: ((kubeconfig))
      WEB_DOMAIN: ((web_domain))
